"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useMemo, useState } from "react";
import { useAuth } from "@/lib/firebase/AuthProvider";
import type { CreativeRoomMode, CreativeRoomResponse } from "@/types/ai";

const MODES: Array<[CreativeRoomMode, string]> = [["openai", "ChatGPT"], ["claude", "Claude"], ["both", "Both"], ["council", "Council"]];
function contextFromPath(pathname: string) { const leaf = pathname.split("/").filter(Boolean).at(-1) ?? "production"; return leaf.split("-").map((word) => word[0]?.toUpperCase() + word.slice(1)).join(" "); }

export function CreativeRoomDock({ productionId }: { productionId: string }) {
  const pathname = usePathname(); const { getIdToken } = useAuth();
  const [open, setOpen] = useState(false); const [mode, setMode] = useState<CreativeRoomMode>("openai"); const [draft, setDraft] = useState(""); const [reply, setReply] = useState(""); const [sending, setSending] = useState(false);
  const context = useMemo(() => contextFromPath(pathname), [pathname]);
  async function send() { if (!draft.trim() || sending) return; setSending(true); setReply(""); try { const token = await getIdToken(); const response = await fetch("/api/creative-room", { method: "POST", headers: { "content-type": "application/json", ...(token ? { authorization: `Bearer ${token}` } : {}) }, body: JSON.stringify({ question: draft.trim(), mode, contextLabel: context, approvedCanon: [], recentHistory: [] }) }); const data = await response.json() as CreativeRoomResponse & { error?: string }; if (!response.ok) throw new Error(data.error ?? "Creative Room could not respond."); setReply(data.responses.map((item) => `${item.role === "openai" ? "ChatGPT" : item.role === "claude" ? "Claude" : "Synthesis"}: ${item.content}`).join("\n\n")); setDraft(""); } catch (error) { setReply(error instanceof Error ? error.message : "Creative Room could not respond."); } finally { setSending(false); } }
  if (pathname.endsWith("/creative-room")) return null;
  return <div className="fixed bottom-5 right-5 z-40">{open && <section className="mb-3 flex h-[34rem] w-[min(25rem,calc(100vw-2rem))] flex-col overflow-hidden rounded-2xl border border-amber-200/20 bg-[#080d1c]/95 shadow-2xl shadow-black/60 backdrop-blur-xl">
    <header className="border-b border-blue-200/10 bg-gradient-to-r from-blue-950/80 to-slate-950 px-4 py-3"><div className="flex items-start justify-between gap-3"><div><p className="text-[9px] font-bold uppercase tracking-[0.25em] text-amber-300">Avrrio Creative Room</p><p className="mt-1 text-xs text-blue-100/55">Context: {context}</p></div><button onClick={() => setOpen(false)} className="text-lg leading-none text-slate-500 hover:text-white" aria-label="Close Creative Room">×</button></div><div className="mt-3 flex gap-1.5">{MODES.map(([id, label]) => <button key={id} onClick={() => setMode(id)} className={`rounded-full px-2.5 py-1 text-[10px] ${mode === id ? "bg-amber-300 text-slate-950" : "bg-white/5 text-slate-400"}`}>{label}</button>)}</div></header>
    <div className="flex-1 overflow-y-auto p-4 text-sm leading-6 text-slate-300">{reply ? <div className="whitespace-pre-wrap rounded-xl border border-blue-200/10 bg-white/[0.03] p-3">{reply}</div> : <div className="mt-16 text-center"><div className="mx-auto mb-3 h-8 w-8 rounded-full border border-amber-300/30 bg-amber-300/5 text-center leading-8 text-amber-300">✦</div><p>Continue developing this part of the story.</p><p className="mt-1 text-xs text-slate-600">Try /continuity, /brainstorm, or /storyboard.</p></div>}</div>
    <footer className="border-t border-blue-200/10 p-3"><textarea value={draft} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void send(); } }} rows={2} placeholder="Talk about the story…" className="w-full resize-none rounded-xl border border-blue-200/10 bg-black/20 px-3 py-2 text-sm text-white outline-none focus:border-amber-300/30" /><div className="mt-2 flex items-center justify-between"><Link href={`/production/${productionId}/creative-room`} className="text-[11px] text-blue-200/45 hover:text-blue-100">Open full history</Link><button onClick={() => void send()} disabled={!draft.trim() || sending} className="rounded-lg bg-amber-300 px-3 py-1.5 text-xs font-bold text-slate-950 disabled:opacity-30">{sending ? "Thinking…" : "Send"}</button></div></footer>
  </section>}<button onClick={() => setOpen((value) => !value)} className="flex items-center gap-2 rounded-full border border-amber-200/25 bg-gradient-to-r from-blue-950 to-slate-950 px-4 py-3 text-sm font-semibold text-slate-100 shadow-xl shadow-black/50 hover:border-amber-200/45"><span className="text-amber-300">✦</span> Creative Room</button></div>;
}

